"""Generate a simulation platform's build/runtime artifacts from a memory map.

Input: a JSON memory map (see the schema below) + the CPU architecture.
Outputs, all derived from the one memory map so the linker and the emulator can
never disagree on the layout:

  * ``<name>.ld``       GNU ld script (drives where the stub's sections land)
  * ``<name>.emu.json`` normalized emulator config (regions/perms/entry/sentinel
                        + arch/cpu + optional timing model) consumed by the
                        Unicorn harness at run time
  * ``<name>.gdb``      GDB ``mem`` layout commands (attach a debugger to the same
                        map the emulator uses)

Memory map schema (JSON)::

    {
      "regions": [
        {"name": "FLASH", "kind": "rom", "origin": "0x00000000", "length": "256K"},
        {"name": "RAM",   "kind": "ram", "origin": "0x20000000", "length": "128K"}
      ],
      "stack": {"length": "8K"},    # carved from the top of the first ram region
      "heap":  {"length": "16K"}    # carved just above .bss in that ram region
    }

The first ``kind: rom`` region holds code + read-only data + the .data initializer
image (LMA); the first ``kind: ram`` region holds .data/.bss, then the heap, with
the stack at its top. Symbols emitted for the runtime + harness: ``_estack``,
``_sim_stack_limit``, ``_sim_heap_start``, ``_sim_heap_end``.
"""

import argparse
import json


def parse_size(v):
    """Accept an int, a hex string, or a K/M-suffixed decimal string."""
    if isinstance(v, int):
        return v
    s = str(v).strip()
    if s.lower().startswith("0x"):
        return int(s, 16)
    mult = 1
    if s and s[-1] in "kKmM":
        mult = 1024 if s[-1] in "kK" else 1024 * 1024
        s = s[:-1]
    return int(s) * mult


# Emulator memory-protection strings <-> the layout. The harness maps them to
# UC_PROT_*. rom is executable+read; ram is read+write+exec (these MCUs run code
# from RAM — RAM vector tables, time-critical funcs copied to SRAM, sim stubs
# staged in scratch); mmio is read+write and routed to a peripheral device model.
_PERM = {"rom": "r-x", "ram": "rwx", "mmio": "rw-"}

# A private, non-mapped-in-firmware page used as the "function returned" sentinel:
# stimuli are called with LR pointing here, so a `bx lr` lands on it and the
# emulator stops. Chosen well clear of the memory map and of ARMv8-M EXC_RETURN
# values (0xFFFFFFxx), which the core would interpret as an exception return.
_SENTINEL_BASE = 0x90000000
_SENTINEL_SIZE = 0x1000


def first_of_kind(regions, kind):
    for r in regions:
        if r.get("kind") == kind:
            return r
    raise SystemExit("memory_map: no region of kind %r" % kind)


def gen_linker_script(mm, arch):
    regions = mm["regions"]
    rom = first_of_kind(regions, "rom")
    ram = first_of_kind(regions, "ram")
    stack_len = parse_size(mm.get("stack", {}).get("length", "0x1000"))
    heap_len = parse_size(mm.get("heap", {}).get("length", "0x2000"))

    lines = []
    lines.append("/* Auto-generated by //rules/sim:gen_platform from the memory map.")
    lines.append("   architecture: %s  —  DO NOT EDIT. */" % arch)
    lines.append("ENTRY(_start)")
    lines.append("")
    lines.append("MEMORY")
    lines.append("{")
    for r in regions:
        if r.get("kind") == "mmio":
            continue  # peripherals aren't linker-allocatable regions
        attrs = "rx" if r.get("kind") == "rom" else "rwx"
        lines.append("    %-8s (%s) : ORIGIN = %s, LENGTH = %d" % (
            r["name"], attrs, hex(parse_size(r["origin"])), parse_size(r["length"])))
    lines.append("}")
    lines.append("")
    lines.append("/* Stack: top %d bytes of %s. Heap: %d bytes just above .bss. */" %
                 (stack_len, ram["name"], heap_len))
    lines.append("_estack = ORIGIN(%s) + LENGTH(%s);" % (ram["name"], ram["name"]))
    lines.append("_sim_stack_size = %d;" % stack_len)
    lines.append("_sim_heap_size  = %d;" % heap_len)
    lines.append("")
    lines.append("SECTIONS")
    lines.append("{")
    lines.append("    .text : {")
    lines.append("        . = ALIGN(4);")
    lines.append("        KEEP(*(.isr_vector))")
    lines.append("        *(.text .text*)")
    lines.append("        *(.rodata .rodata*)")
    lines.append("        KEEP(*(.init)) KEEP(*(.fini))")
    lines.append("        . = ALIGN(4);")
    lines.append("        _etext = .;")
    lines.append("    } > %s" % rom["name"])
    lines.append("")
    lines.append("    .ARM.exidx : { *(.ARM.exidx*) } > %s" % rom["name"])
    lines.append("")
    lines.append("    /* .data: initialized RAM, LMA in %s, copied by sim_rt/_start. */" % rom["name"])
    lines.append("    _sidata = LOADADDR(.data);")
    lines.append("    .data : {")
    lines.append("        . = ALIGN(4);")
    lines.append("        __data_start__ = .;")
    lines.append("        *(.data .data*)")
    lines.append("        . = ALIGN(4);")
    lines.append("        __data_end__ = .;")
    lines.append("    } > %s AT > %s" % (ram["name"], rom["name"]))
    lines.append("")
    lines.append("    .bss (NOLOAD) : {")
    lines.append("        . = ALIGN(4);")
    lines.append("        __bss_start__ = .;")
    lines.append("        *(.bss .bss*) *(COMMON)")
    lines.append("        . = ALIGN(8);")
    lines.append("        __bss_end__ = .;")
    lines.append("    } > %s" % ram["name"])
    lines.append("")
    lines.append("    /* Heap region owned by sim_rt's bump allocator (+ max_dynamic canary). */")
    lines.append("    .sim_heap (NOLOAD) : {")
    lines.append("        . = ALIGN(8);")
    lines.append("        _sim_heap_start = .;")
    lines.append("        . = . + _sim_heap_size;")
    lines.append("        . = ALIGN(8);")
    lines.append("        _sim_heap_end = .;")
    lines.append("    } > %s" % ram["name"])
    lines.append("")
    lines.append("    .ARM.attributes 0 : { *(.ARM.attributes) }")
    lines.append("}")
    lines.append("")
    # Top-level (outside SECTIONS): the stack floor + a link-time guard that the
    # heap doesn't run into the stack. GNU ld rejects a bare ASSERT statement
    # inside SECTIONS, so both live here.
    lines.append("_sim_stack_limit = _estack - _sim_stack_size;")
    lines.append('ASSERT(_sim_heap_end <= _sim_stack_limit, "sim: heap overruns stack");')
    lines.append("")
    return "\n".join(lines)


def gen_emu_config(mm, arch, timing):
    regions = []
    rom = None
    for r in mm["regions"]:
        kind = r.get("kind")
        if kind == "rom" and rom is None:
            rom = r
        regions.append({
            "name": r["name"],
            "base": parse_size(r["origin"]),
            "size": parse_size(r["length"]),
            "perm": _PERM.get(kind, "rw-"),
            "load": kind == "rom",
            "mmio": kind == "mmio",
        })
    cfg = {
        "architecture": arch,
        "regions": regions,
        "sentinel": {"base": _SENTINEL_BASE, "size": _SENTINEL_SIZE},
        # Full-app mode: "reset" boots from the vector table (SP=word0, PC=word1);
        # "none" (default) means the harness calls functions directly (stub mode).
        "boot": mm.get("boot", "none"),
        # Vector table location: a memory_map override (an address string or a
        # symbol name, e.g. "__VECTOR_TABLE" when it isn't at the flash origin —
        # the RP2350 puts it after its boot metadata), else the first rom origin.
        "vector_table": mm.get("vector_table",
                               parse_size(rom["origin"]) if rom else 0),
        # Full-app mode: when true, the harness stands up the Cortex-M interrupt
        # controller (NVIC + SysTick + exception entry/return) so interrupt-driven
        # firmware makes progress; peripheral models raise IRQs via uc.nvic.
        "interrupts": bool(mm.get("interrupts", False)),
    }
    if timing:
        cfg["timing_model"] = timing
    return cfg


def gen_gdb(mm):
    out = ["# Auto-generated GDB memory layout (//rules/sim:gen_platform)."]
    for r in mm["regions"]:
        base = parse_size(r["origin"])
        end = base + parse_size(r["length"])
        mode = "ro" if r.get("kind") == "rom" else "rw"
        out.append("mem %s %s %s" % (hex(base), hex(end), mode))
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--memory_map", required=True)
    ap.add_argument("--architecture", required=True)
    ap.add_argument("--timing_model", default="")
    ap.add_argument("--out_ld", required=True)
    ap.add_argument("--out_emu", required=True)
    ap.add_argument("--out_gdb", required=True)
    args = ap.parse_args()

    with open(args.memory_map) as f:
        mm = json.load(f)
    timing = None
    if args.timing_model:
        with open(args.timing_model) as f:
            timing = json.load(f)

    with open(args.out_ld, "w") as f:
        f.write(gen_linker_script(mm, args.architecture))
    with open(args.out_emu, "w") as f:
        json.dump(gen_emu_config(mm, args.architecture, timing), f, indent=2)
    with open(args.out_gdb, "w") as f:
        f.write(gen_gdb(mm))


if __name__ == "__main__":
    main()
