# GENERATED scaffold for @arduino_esp32 (merged core + esp32c6 SDK). Edit as needed.
# Compile: includes/defines as native attrs (propagate to the app); per-language
# std flags. Link: -L dirs computed at build time + the shipped ld_* response
# files, in a --start-group with the SDK archives.
package(default_visibility = ["//visibility:public"])

# -L dirs for lib/, ld/, and the memory-type dir, from real staged paths.
genrule(
    name = "sdk_link_dirs",
    srcs = [
        "sdk/esp32c6/lib/libriscv.a",
        "sdk/esp32c6/ld/memory.ld",
        "sdk/esp32c6/qio_qspi/libspi_flash.a",
    ],
    outs = ["sdk_link_dirs.rsp"],
    cmd = ("echo \"-L$$(dirname $(location sdk/esp32c6/lib/libriscv.a))\" > $@ && " +
           "echo \"-L$$(dirname $(location sdk/esp32c6/ld/memory.ld))\" >> $@ && " +
           "echo \"-L$$(dirname $(location sdk/esp32c6/qio_qspi/libspi_flash.a))\" >> $@"),
)

filegroup(name = "sdk_libs", srcs = glob([
    "sdk/esp32c6/lib/*.a",
    "sdk/esp32c6/qio_qspi/*.a",
    "sdk/esp32c6/ld/*.a",  # libphy.a, libbtbb.a live alongside the ld scripts
]))
filegroup(name = "sdk_ld", srcs = glob(["sdk/esp32c6/ld/*.ld"]))
filegroup(name = "ld_flags", srcs = ["sdk/esp32c6/flags/ld_flags"])
filegroup(name = "ld_scripts", srcs = ["sdk/esp32c6/flags/ld_scripts"])
filegroup(name = "ld_libs", srcs = ["sdk/esp32c6/flags/ld_libs"])

# Prebuilt pieces needed to assemble a bootable flash image (see esptool_flash).
filegroup(name = "bootloader_elf", srcs = ["sdk/esp32c6/bin/bootloader_qio_80m.elf"])

# Generate the partition table from the CSV like the IDE does. The repo's
# shipped tools/partitions/default.bin is stale: old layout and no trailing MD5
# row, which IDF >= 5 partition loading requires (load fails with 0x105).
genrule(
    name = "partitions_default",
    srcs = ["tools/partitions/default.csv"],
    outs = ["partitions_default.bin"],
    cmd = "python3 $(location :gen_esp32part) -q $(location tools/partitions/default.csv) $@",
    tools = [":gen_esp32part"],
)

# Single-app layout (no OTA slots): app0 grows to 0x200000 — for apps that
# outgrow default.csv's 0x140000 slot (WiFi + webserver + FastLED + a
# protocol stack lands around 1.5 MB). Same nvs/otadata/app0 offsets, so
# esptool_flash needs only `partitions = ...` overridden.
genrule(
    name = "partitions_no_ota",
    srcs = ["tools/partitions/no_ota.csv"],
    outs = ["partitions_no_ota.bin"],
    cmd = "python3 $(location :gen_esp32part) -q $(location tools/partitions/no_ota.csv) $@",
    tools = [":gen_esp32part"],
)

filegroup(name = "gen_esp32part", srcs = ["tools/gen_esp32part.py"])

filegroup(name = "boot_app0", srcs = ["tools/partitions/boot_app0.bin"])

# Header + include-path + define carrier (propagates to dependents incl. the app).
cc_library(
    name = "sdk_hdrs",
    hdrs = glob(
        ["sdk/esp32c6/include/**/*.h", "sdk/esp32c6/qio_qspi/include/**/*.h",
         "cores/esp32/**/*.h", "variants/esp32c6/**/*.h", "sdk/esp32c6/include/**/*.hpp",
         "libraries/SPI/**/*.h"],
        allow_empty = True,
    ),
    includes = [
        "sdk/esp32c6/include/newlib/platform_include",
        "sdk/esp32c6/include/freertos/config/include",
        "sdk/esp32c6/include/freertos/config/include/freertos",
        "sdk/esp32c6/include/freertos/config/riscv/include",
        "sdk/esp32c6/include/freertos/FreeRTOS-Kernel/include",
        "sdk/esp32c6/include/freertos/FreeRTOS-Kernel/portable/riscv/include",
        "sdk/esp32c6/include/freertos/FreeRTOS-Kernel/portable/riscv/include/freertos",
        "sdk/esp32c6/include/freertos/esp_additions/include",
        "sdk/esp32c6/include/esp_hw_support/include",
        "sdk/esp32c6/include/esp_hw_support/include/soc",
        "sdk/esp32c6/include/esp_hw_support/include/soc/esp32c6",
        "sdk/esp32c6/include/esp_hw_support/dma/include",
        "sdk/esp32c6/include/esp_hw_support/ldo/include",
        "sdk/esp32c6/include/esp_hw_support/debug_probe/include",
        "sdk/esp32c6/include/esp_hw_support/mspi_timing_tuning/include",
        "sdk/esp32c6/include/esp_hw_support/mspi_timing_tuning/tuning_scheme_impl/include",
        "sdk/esp32c6/include/esp_hw_support/power_supply/include",
        "sdk/esp32c6/include/esp_hw_support/port/esp32c6",
        "sdk/esp32c6/include/esp_hw_support/port/esp32c6/include",
        "sdk/esp32c6/include/esp_hw_support/port/esp32c6/private_include",
        "sdk/esp32c6/include/heap/include",
        "sdk/esp32c6/include/heap/tlsf",
        "sdk/esp32c6/include/log/include",
        "sdk/esp32c6/include/soc/include",
        "sdk/esp32c6/include/soc/esp32c6",
        "sdk/esp32c6/include/soc/esp32c6/include",
        "sdk/esp32c6/include/soc/esp32c6/register",
        "sdk/esp32c6/include/hal/platform_port/include",
        "sdk/esp32c6/include/hal/esp32c6/include",
        "sdk/esp32c6/include/hal/include",
        "sdk/esp32c6/include/esp_rom/include",
        "sdk/esp32c6/include/esp_rom/esp32c6/include",
        "sdk/esp32c6/include/esp_rom/esp32c6/include/esp32c6",
        "sdk/esp32c6/include/esp_rom/esp32c6",
        "sdk/esp32c6/include/esp_common/include",
        "sdk/esp32c6/include/esp_system/include",
        "sdk/esp32c6/include/esp_system/port/include/riscv",
        "sdk/esp32c6/include/esp_system/port/include/private",
        "sdk/esp32c6/include/riscv/include",
        "sdk/esp32c6/include/esp_timer/include",
        "sdk/esp32c6/include/lwip/include",
        "sdk/esp32c6/include/lwip/include/apps",
        "sdk/esp32c6/include/lwip/include/apps/sntp",
        "sdk/esp32c6/include/lwip/lwip/src/include",
        "sdk/esp32c6/include/lwip/port/include",
        "sdk/esp32c6/include/lwip/port/freertos/include",
        "sdk/esp32c6/include/lwip/port/esp32xx/include",
        "sdk/esp32c6/include/lwip/port/esp32xx/include/arch",
        "sdk/esp32c6/include/lwip/port/esp32xx/include/sys",
        "sdk/esp32c6/include/espressif__esp-tflite-micro",
        "sdk/esp32c6/include/espressif__esp-tflite-micro/third_party/gemmlowp",
        "sdk/esp32c6/include/espressif__esp-tflite-micro/third_party/flatbuffers/include",
        "sdk/esp32c6/include/espressif__esp-tflite-micro/third_party/ruy",
        "sdk/esp32c6/include/espressif__esp-tflite-micro/third_party/kissfft",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/app/ember_coupling",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/include",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/lib",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/lib/dnssd",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/OpenThread",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/jsoncpp/repo/include",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/nlfaultinjection/include",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/nlassert/repo/include",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/third_party/nlio/repo/include",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/zzz_generated/app-common",
        "sdk/esp32c6/include/esp-idf/espressif__esp_matter",
        "sdk/esp32c6/include/esp_matter/zap_common",
        "sdk/esp32c6/include/esp_matter",
        "sdk/esp32c6/include/esp_matter/utils",
        "sdk/esp32c6/include/esp_matter_bridge",
        "sdk/esp32c6/include/esp_matter_console",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32/nimble",
        "sdk/esp32c6/include/espressif__esp_matter/connectedhomeip/connectedhomeip/src/platform/ESP32/route_hook",
        "sdk/esp32c6/include/esp_eth/include",
        "sdk/esp32c6/include/esp_event/include",
        "sdk/esp32c6/include/esp_driver_spi/include",
        "sdk/esp32c6/include/esp_pm/include",
        "sdk/esp32c6/include/bt/include/esp32c6/include",
        "sdk/esp32c6/include/bt/common/osi/include",
        "sdk/esp32c6/include/bt/common/api/include/api",
        "sdk/esp32c6/include/bt/common/btc/profile/esp/blufi/include",
        "sdk/esp32c6/include/bt/common/btc/profile/esp/include",
        "sdk/esp32c6/include/bt/common/hci_log/include",
        "sdk/esp32c6/include/bt/common/ble_log/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/common/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/core",
        "sdk/esp32c6/include/bt/esp_ble_mesh/core/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/core/storage",
        "sdk/esp32c6/include/bt/esp_ble_mesh/btc/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/models/common/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/models/client/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/models/server/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/api/core/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/api/models/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/api",
        "sdk/esp32c6/include/bt/esp_ble_mesh/lib/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/v1.1/api/core/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/v1.1/api/models/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/v1.1/btc/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/v1.1/include",
        "sdk/esp32c6/include/bt/esp_ble_mesh/v1.1/dfu",
        "sdk/esp32c6/include/bt/esp_ble_mesh/v1.1/mbt",
        "sdk/esp32c6/include/bt/host/nimble/port/include",
        "sdk/esp32c6/include/bt/porting/include",
        "sdk/esp32c6/include/bt/porting/npl/freertos/include",
        "sdk/esp32c6/include/bt/porting/transport/include",
        "sdk/esp32c6/include/bt/common/tinycrypt/include",
        "sdk/esp32c6/include/bt/common/tinycrypt/port",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/ans/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/bas/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/dis/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/gap/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/gatt/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/hr/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/htp/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/ias/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/ipss/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/lls/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/prox/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/cts/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/tps/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/hid/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/sps/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/cte/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/util/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/store/ram/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/store/config/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/host/services/ras/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/porting/nimble/include",
        "sdk/esp32c6/include/bt/host/nimble/nimble/nimble/transport/include",
        "sdk/esp32c6/include/esp_wifi/include",
        "sdk/esp32c6/include/esp_wifi/include/local",
        "sdk/esp32c6/include/esp_wifi/wifi_apps/include",
        "sdk/esp32c6/include/esp_wifi/wifi_apps/nan_app/include",
        "sdk/esp32c6/include/esp_phy/include",
        "sdk/esp32c6/include/esp_phy/esp32c6/include",
        "sdk/esp32c6/include/esp_netif/include",
        "sdk/esp32c6/include/mbedtls/port/include",
        "sdk/esp32c6/include/mbedtls/mbedtls/include",
        "sdk/esp32c6/include/mbedtls/mbedtls/library",
        "sdk/esp32c6/include/mbedtls/esp_crt_bundle/include",
        "sdk/esp32c6/include/mbedtls/mbedtls/3rdparty/everest/include",
        "sdk/esp32c6/include/mbedtls/mbedtls/3rdparty/p256-m",
        "sdk/esp32c6/include/mbedtls/mbedtls/3rdparty/p256-m/p256-m",
        "sdk/esp32c6/include/fatfs/diskio",
        "sdk/esp32c6/include/fatfs/src",
        "sdk/esp32c6/include/fatfs/vfs",
        "sdk/esp32c6/include/wear_levelling/include",
        "sdk/esp32c6/include/esp_partition/include",
        "sdk/esp32c6/include/sdmmc/include",
        "sdk/esp32c6/include/esp_driver_sdmmc/include",
        "sdk/esp32c6/include/esp_driver_gpio/include",
        "sdk/esp32c6/include/esp_driver_sdspi/include",
        "sdk/esp32c6/include/app_update/include",
        "sdk/esp32c6/include/bootloader_support/include",
        "sdk/esp32c6/include/bootloader_support/bootloader_flash/include",
        "sdk/esp32c6/include/esp_app_format/include",
        "sdk/esp32c6/include/esp_bootloader_format/include",
        "sdk/esp32c6/include/console",
        "sdk/esp32c6/include/vfs/include",
        "sdk/esp32c6/include/esp_vfs_console/include",
        "sdk/esp32c6/include/openthread/include",
        "sdk/esp32c6/include/openthread/openthread/include",
        "sdk/esp32c6/include/esp_driver_uart/include",
        "sdk/esp32c6/include/driver/deprecated",
        "sdk/esp32c6/include/driver/i2c/include",
        "sdk/esp32c6/include/driver/touch_sensor/include",
        "sdk/esp32c6/include/driver/twai/include",
        "sdk/esp32c6/include/esp_ringbuf/include",
        "sdk/esp32c6/include/esp_driver_pcnt/include",
        "sdk/esp32c6/include/esp_driver_gptimer/include",
        "sdk/esp32c6/include/esp_driver_mcpwm/include",
        "sdk/esp32c6/include/esp_driver_ana_cmpr/include",
        "sdk/esp32c6/include/esp_driver_i2s/include",
        "sdk/esp32c6/include/esp_driver_sdio/include",
        "sdk/esp32c6/include/esp_driver_dac/include",
        "sdk/esp32c6/include/esp_driver_rmt/include",
        "sdk/esp32c6/include/esp_driver_tsens/include",
        "sdk/esp32c6/include/esp_driver_sdm/include",
        "sdk/esp32c6/include/esp_driver_i2c/include",
        "sdk/esp32c6/include/esp_driver_ledc/include",
        "sdk/esp32c6/include/esp_driver_parlio/include",
        "sdk/esp32c6/include/esp_driver_usb_serial_jtag/include",
        "sdk/esp32c6/include/esp_driver_twai/include",
        "sdk/esp32c6/include/nvs_flash/include",
        "sdk/esp32c6/include/spi_flash/include",
        "sdk/esp32c6/include/espressif__esp_secure_cert_mgr/include",
        "sdk/esp32c6/include/espressif__json_parser/include",
        "sdk/esp32c6/include/espressif__jsmn/include",
        "sdk/esp32c6/include/spiffs/include",
        "sdk/esp32c6/include/esp_http_client/include",
        "sdk/esp32c6/include/espressif__json_generator/include",
        "sdk/esp32c6/include/json/cJSON",
        "sdk/esp32c6/include/espressif__mdns/include",
        "sdk/esp32c6/include/espressif__esp_delta_ota/include",
        "sdk/esp32c6/include/espressif__esp_encrypted_img/include",
        "sdk/esp32c6/include/espressif__esp_insights/include",
        "sdk/esp32c6/include/espressif__esp_diagnostics/include",
        "sdk/esp32c6/include/efuse/include",
        "sdk/esp32c6/include/efuse/esp32c6/include",
        "sdk/esp32c6/include/esp_mm/include",
        "sdk/esp32c6/include/esp_security/include",
        "sdk/esp32c6/include/pthread/include",
        "sdk/esp32c6/include/esp_psram/include",
        "sdk/esp32c6/include/app_trace/include",
        "sdk/esp32c6/include/wpa_supplicant/include",
        "sdk/esp32c6/include/wpa_supplicant/port/include",
        "sdk/esp32c6/include/wpa_supplicant/esp_supplicant/include",
        "sdk/esp32c6/include/esp_coex/include",
        "sdk/esp32c6/include/esp_gdbstub/include",
        "sdk/esp32c6/include/unity/include",
        "sdk/esp32c6/include/unity/unity/src",
        "sdk/esp32c6/include/cmock/CMock/src",
        "sdk/esp32c6/include/esp_driver_bitscrambler/include",
        "sdk/esp32c6/include/http_parser",
        "sdk/esp32c6/include/esp-tls",
        "sdk/esp32c6/include/esp-tls/esp-tls-crypto",
        "sdk/esp32c6/include/esp_adc/include",
        "sdk/esp32c6/include/esp_adc/interface",
        "sdk/esp32c6/include/esp_adc/esp32c6/include",
        "sdk/esp32c6/include/esp_adc/deprecated/include",
        "sdk/esp32c6/include/esp_driver_isp/include",
        "sdk/esp32c6/include/esp_driver_cam/include",
        "sdk/esp32c6/include/esp_driver_cam/interface",
        "sdk/esp32c6/include/esp_driver_jpeg/include",
        "sdk/esp32c6/include/esp_driver_ppa/include",
        "sdk/esp32c6/include/esp_hal_ieee802154/include",
        "sdk/esp32c6/include/esp_hal_ieee802154/esp32c6/include",
        "sdk/esp32c6/include/esp_hid/include",
        "sdk/esp32c6/include/tcp_transport/include",
        "sdk/esp32c6/include/esp_http_server/include",
        "sdk/esp32c6/include/esp_https_ota/include",
        "sdk/esp32c6/include/esp_https_server/include",
        "sdk/esp32c6/include/esp_lcd/include",
        "sdk/esp32c6/include/esp_lcd/interface",
        "sdk/esp32c6/include/protobuf-c/protobuf-c",
        "sdk/esp32c6/include/protocomm/include/common",
        "sdk/esp32c6/include/protocomm/include/security",
        "sdk/esp32c6/include/protocomm/include/transports",
        "sdk/esp32c6/include/protocomm/include/crypto/srp6a",
        "sdk/esp32c6/include/protocomm/proto-c",
        "sdk/esp32c6/include/esp_local_ctrl/include",
        "sdk/esp32c6/include/esp_tee/include",
        "sdk/esp32c6/include/espcoredump/include",
        "sdk/esp32c6/include/espcoredump/include/port/riscv",
        "sdk/esp32c6/include/idf_test/include",
        "sdk/esp32c6/include/idf_test/include/esp32c6",
        "sdk/esp32c6/include/ieee802154/include",
        "sdk/esp32c6/include/mqtt/esp-mqtt/include",
        "sdk/esp32c6/include/nvs_sec_provider/include",
        "sdk/esp32c6/include/rt/include",
        "sdk/esp32c6/include/wifi_provisioning/include",
        "sdk/esp32c6/include/espressif__esp-nn/include",
        "sdk/esp32c6/include/espressif__esp-nn/src/common",
        "sdk/esp32c6/include/espressif__rmaker_common/include",
        "sdk/esp32c6/include/espressif__cbor/tinycbor/src",
        "sdk/esp32c6/include/espressif__esp_diag_data_store/src/rtc_store",
        "sdk/esp32c6/include/espressif__esp_diag_data_store/include",
        "sdk/esp32c6/include/espressif__esp-serial-flasher/include",
        "sdk/esp32c6/include/espressif__esp-serial-flasher/port",
        "sdk/esp32c6/include/espressif__esp_rcp_update/include",
        "sdk/esp32c6/include/chmorgan__esp-libhelix-mp3/libhelix-mp3/pub",
        "sdk/esp32c6/include/espressif__esp-modbus/modbus/mb_transports",
        "sdk/esp32c6/include/espressif__esp-modbus/modbus/mb_controller/common/include",
        "sdk/esp32c6/include/espressif__esp-modbus/modbus/mb_objects/common",
        "sdk/esp32c6/include/espressif__esp-modbus/modbus/mb_ports/common",
        "sdk/esp32c6/include/espressif__esp-modbus/modbus/mb_ports/serial",
        "sdk/esp32c6/include/espressif__esp-modbus/modbus/mb_ports/tcp",
        "sdk/esp32c6/include/espressif__esp-zboss-lib/include",
        "sdk/esp32c6/include/espressif__esp-zigbee-lib/include",
        "sdk/esp32c6/include/espressif__libsodium/port_include",
        "sdk/esp32c6/include/espressif__libsodium/libsodium/src/libsodium/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/dotprod/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/support/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/support/mem/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/hann/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/blackman/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/blackman_harris/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/blackman_nuttall/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/nuttall/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/windows/flat_top/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/iir/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/fir/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/add/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/sub/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/mul/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/addc/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/mulc/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/math/sqrt/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/mul/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/add/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/addc/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/mulc/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/sub/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/fft/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/dct/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/conv/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/common/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/matrix/mul/test/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/kalman/ekf/include",
        "sdk/esp32c6/include/espressif__esp-dsp/modules/kalman/ekf_imu13states/include",
        "sdk/esp32c6/include/espressif__esp_modem/include",
        "sdk/esp32c6/include/espressif__esp_modem/command/include",
        "sdk/esp32c6/include/espressif__esp_schedule/include",
        "sdk/esp32c6/include/espressif__network_provisioning/include",
        "sdk/esp32c6/include/espressif__esp_rainmaker/include",
        "sdk/esp32c6/include/espressif__qrcode/include",
        "sdk/esp32c6/include/joltwallet__littlefs/include",
        "sdk/esp32c6/include/fb_gfx/include",
        "sdk/esp32c6/qio_qspi/include",
        "cores/esp32",
        "variants/esp32c6",
        "libraries/SPI/src",  # FastLED's ESP32 SPI shim includes <SPI.h>
    ],
    defines = [
        "ESP32_ARDUINO_LIB_BUILDER",
        "ESP_PLATFORM",
        "MB_MDNS_IS_INCLUDED",
        "MD5_ENABLED=1",
        "OPENTHREAD_FTD=1",
        "SERIAL_FLASHER_BOOT_HOLD_TIME_MS=50",
        "SERIAL_FLASHER_RESET_HOLD_TIME_MS=100",
        "SOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE",
        "SOC_XTAL_FREQ_MHZ=CONFIG_XTAL_FREQ",
        "UNITY_INCLUDE_CONFIG_H",
        "_GLIBCXX_HAVE_POSIX_SEMAPHORE",
        "_GLIBCXX_USE_POSIX_SEMAPHORE",
        "_GNU_SOURCE",
        "_POSIX_READER_WRITER_LOCKS",
        "TF_LITE_STATIC_MEMORY",
        "CHIP_CONFIG_SOFTWARE_VERSION_NUMBER=0",
        "CHIP_DNSSD_DEFAULT_PLATFORM=true",
        "CHIP_DNSSD_DEFAULT_NONE=false",
        "CHIP_DNSSD_DEFAULT_MINIMAL=false",
        "F_CPU=160000000L",
        "ARDUINO=10812",
        "ARDUINO_ESP32C6_DEV",
        "ARDUINO_ARCH_ESP32",
        "ARDUINO_PARTITION_default",
        'ARDUINO_BOARD=\\"ESP32C6_DEV\\"',
        'ARDUINO_VARIANT=\\"esp32c6\\"',
        # From platform.txt build.extra_flags — ESP32=ESP32 is what libraries
        # (e.g. FastLED) key off for platform detection.
        "ESP32=ESP32",
        "CORE_DEBUG_LEVEL=0",
        "ARDUINO_USB_MODE=1",
        "ARDUINO_USB_CDC_ON_BOOT=1",
    ],
)

_C_COPTS = [
        "-march=rv32imac_zicsr_zifencei",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-error=unused-function",
        "-Wno-error=unused-variable",
        "-Wno-error=unused-but-set-variable",
        "-Wno-error=deprecated-declarations",
        "-Wno-error=extra",
        "-Wno-unused-parameter",
        "-Wno-sign-compare",
        "-Wno-enum-conversion",
        "-gdwarf-4",
        "-ggdb",
        "-freorder-blocks",
        "-Wwrite-strings",
        "-fstack-protector",
        "-fstrict-volatile-bitfields",
        "-fno-jump-tables",
        "-fno-tree-switch-conversion",
        "-Wno-old-style-declaration",
        "-DCHIP_HAVE_CONFIG_H",
        "-Wno-strict-prototypes",
        "-std=gnu17",
        "-w",
    ]

_CXX_COPTS = [
        "-march=rv32imac_zicsr_zifencei",
        "-fno-rtti",
        "-ffunction-sections",
        "-fdata-sections",
        "-Wno-error=unused-function",
        "-Wno-error=unused-variable",
        "-Wno-error=unused-but-set-variable",
        "-Wno-error=deprecated-declarations",
        "-Wno-error=extra",
        "-Wno-unused-parameter",
        "-Wno-sign-compare",
        "-Wno-enum-conversion",
        "-gdwarf-4",
        "-ggdb",
        "-freorder-blocks",
        "-Wwrite-strings",
        "-fstack-protector",
        "-fstrict-volatile-bitfields",
        "-fno-jump-tables",
        "-fno-tree-switch-conversion",
        "-fexceptions",
        "-fuse-cxa-atexit",
        "-DCHIP_HAVE_CONFIG_H",
        "-std=gnu++2b",
        "-w",
    ]

cc_library(
    name = "core_c",
    srcs = glob(["cores/esp32/**/*.c", "variants/esp32c6/**/*.c"], allow_empty = True),
    copts = _C_COPTS,
    # Force all core objects in: the core HAL (.c) and Arduino API (.cpp) call
    # each other, so split archives would drop objects to the wrong link order.
    alwayslink = True,
    deps = [":sdk_hdrs"],
)

cc_library(
    name = "core_cpp",
    srcs = glob(["cores/esp32/**/*.cpp", "variants/esp32c6/**/*.cpp", "libraries/SPI/**/*.cpp"], allow_empty = True),
    copts = _CXX_COPTS,
    alwayslink = True,
    deps = [":sdk_hdrs"],
)

# Bundled Arduino libraries (beyond SPI, which rides along in the core above).
# Each mirrors libraries/<X>/src. Header-only plumbing (esp32-hal, IDF) comes
# from :sdk_hdrs; inter-library deps mirror their #includes.
cc_library(
    name = "network",
    srcs = glob(["libraries/Network/src/**/*.cpp"], allow_empty = True),
    hdrs = glob(["libraries/Network/src/**/*.h"], allow_empty = True),
    includes = ["libraries/Network/src"],
    copts = _CXX_COPTS,
    deps = [":sdk_hdrs"],
)

cc_library(
    name = "fs",
    srcs = glob(["libraries/FS/src/**/*.cpp"], allow_empty = True),
    hdrs = glob(["libraries/FS/src/**/*.h"], allow_empty = True),
    includes = ["libraries/FS/src"],
    copts = _CXX_COPTS,
    deps = [":sdk_hdrs"],
)

cc_library(
    name = "wifi",
    srcs = glob(["libraries/WiFi/src/**/*.cpp"], allow_empty = True),
    hdrs = glob(["libraries/WiFi/src/**/*.h"], allow_empty = True),
    includes = ["libraries/WiFi/src"],
    copts = _CXX_COPTS,
    deps = [
        ":network",
        ":sdk_hdrs",
    ],
)

cc_library(
    name = "hash",
    srcs = glob(["libraries/Hash/src/**/*.cpp"], allow_empty = True),
    hdrs = glob(["libraries/Hash/src/**/*.h"], allow_empty = True),
    includes = ["libraries/Hash/src"],
    copts = _CXX_COPTS,
    deps = [":sdk_hdrs"],
)

cc_library(
    name = "webserver",
    srcs = glob(["libraries/WebServer/src/**/*.cpp"], allow_empty = True),
    hdrs = glob(["libraries/WebServer/src/**/*.h"], allow_empty = True),
    includes = ["libraries/WebServer/src"],
    copts = _CXX_COPTS,
    deps = [
        ":fs",
        ":hash",
        ":network",
        ":sdk_hdrs",
    ],
)

# The linkable core: carries the IDF link recipe (recipe.c.combine + ld_flags).
cc_library(
    name = "core",
    additional_linker_inputs = [
        ":sdk_link_dirs", ":sdk_libs", ":sdk_ld",
        ":ld_flags", ":ld_scripts", ":ld_libs",
    ],
    linkopts = [
        "@$(location :sdk_link_dirs)",
        "@$(location :ld_flags)",
        "@$(location :ld_scripts)",
        "-Wl,--wrap=esp_panic_handler",
        "-Wl,--wrap=esp_bt_mem_release",
        "-Wl,--wrap=esp_bt_controller_mem_release",
        "-Wl,--start-group",
        "@$(location :ld_libs)",
        "-Wl,--end-group",
        "-Wl,-EL",
    ],
    deps = [":core_c", ":core_cpp", ":sdk_hdrs"],
)
