"""`arduino_library`: pull a third-party Arduino library from a .zip and
code-generate a BUILD that compiles it as a native cc_library.

Arduino libraries follow a conventional layout — sources + headers under `src/`
(occasionally at the root) — so we can generate a `cc_library` mechanically:
glob `src/**` for srcs/hdrs and expose `src` as the include dir. Use this for
add-on libraries; the arduino-pico *core* itself comes in via Nix
(nix/arduino_pico.nix), not this rule.

Example (in MODULE.bazel, via the `arduino` extension in rules/extensions.bzl):

    arduino = use_extension("//rules:extensions.bzl", "arduino")
    arduino.library(
        name = "Adafruit_NeoPixel",
        urls = ["https://github.com/adafruit/Adafruit_NeoPixel/archive/1.12.3.zip"],
        sha256 = "....",
        strip_prefix = "Adafruit_NeoPixel-1.12.3",
        deps = ["@arduino_pico//:core"],
    )
    use_repo(arduino, "Adafruit_NeoPixel")
"""

_BUILD_TEMPLATE = """# GENERATED by arduino_library -- do not edit by hand.
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "{name}",
    srcs = glob(
        [
{src_globs}
        ],
        allow_empty = True,
    ),
    hdrs = glob(
        [
{hdr_globs}
        ],
        allow_empty = True,
    ),
    includes = {includes},
    copts = {copts},
    defines = {defines},
    deps = {deps},
)

alias(
    name = "library",
    actual = ":{name}",
)
"""

def _render_list(items):
    return "[" + ", ".join(['"%s"' % i for i in items]) + "]"

def _render_globs(dirs, exts, indent):
    lines = []
    for d in dirs:
        for ext in exts:
            lines.append('%s"%s/**/*.%s",' % (indent, d, ext))
    return "\n".join(lines)

def _arduino_library_impl(ctx):
    urls = ctx.attr.urls or ([ctx.attr.url] if ctx.attr.url else [])
    if not urls:
        fail("arduino_library %s: set `url` or `urls`" % ctx.name)

    ctx.download_and_extract(
        url = urls,
        sha256 = ctx.attr.sha256,
        stripPrefix = ctx.attr.strip_prefix,
    )

    src_dirs = ctx.attr.src_dirs
    build = _BUILD_TEMPLATE.format(
        name = ctx.attr.lib_name or ctx.name,
        src_globs = _render_globs(src_dirs, ["c", "cpp", "cc", "S"], " " * 12),
        hdr_globs = _render_globs(src_dirs, ["h", "hpp"], " " * 12),
        includes = _render_list(src_dirs),
        copts = _render_list(ctx.attr.copts),
        defines = _render_list(ctx.attr.defines),
        deps = _render_list(ctx.attr.deps),
    )
    ctx.file("BUILD.bazel", build)

arduino_library = repository_rule(
    implementation = _arduino_library_impl,
    attrs = {
        "url": attr.string(),
        "urls": attr.string_list(),
        "sha256": attr.string(),
        "strip_prefix": attr.string(),
        "lib_name": attr.string(doc = "cc_library target name (defaults to repo name)."),
        "src_dirs": attr.string_list(
            default = ["src"],
            doc = "Dirs (relative to the extracted root) to glob + expose as includes.",
        ),
        "copts": attr.string_list(default = []),
        "defines": attr.string_list(default = []),
        "deps": attr.string_list(default = []),
    },
)
