"""Codegen for c_resource_library: embed files as C const char arrays.

Usage:
  resource_gen.py --name NAME --out-dir DIR FILE...

Writes DIR/NAME.h and DIR/NAME.c. Each input FILE becomes:
  const char <sym>[]      -- file bytes, NUL-terminated (binary-safe)
  const size_t <sym>_len  -- length in bytes, excluding the trailing NUL
where <sym> is the file's basename with non-alphanumerics mapped to '_'
(e.g. page.html -> page_html).
"""

import argparse
import os
import re


def symbol_for(path):
    sym = re.sub(r"[^0-9a-zA-Z]", "_", os.path.basename(path))
    if sym[0].isdigit():
        sym = "_" + sym
    return sym


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("files", nargs="+")
    args = parser.parse_args()

    guard = re.sub(r"[^0-9a-zA-Z]", "_", args.name).upper() + "_RESOURCES_H_"
    header = [
        "// GENERATED by //rules:resource_gen.py -- do not edit.",
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "#include <stddef.h>",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
    ]
    source = [
        "// GENERATED by //rules:resource_gen.py -- do not edit.",
        '#include "%s.h"' % args.name,
    ]

    seen = {}
    for path in args.files:
        sym = symbol_for(path)
        if sym in seen:
            raise SystemExit(
                "resource symbol collision: %s and %s both map to '%s'"
                % (seen[sym], path, sym)
            )
        seen[sym] = path
        with open(path, "rb") as f:
            data = f.read()
        header.append("extern const char %s[];" % sym)
        header.append("extern const size_t %s_len;" % sym)
        rows = []
        for i in range(0, len(data), 12):
            rows.append("    " + ", ".join("0x%02x" % b for b in data[i : i + 12]) + ",")
        source.append("const char %s[] = {" % sym)
        source.extend(rows)
        source.append("    0x00,  // NUL so the data doubles as a C string")
        source.append("};")
        source.append("const size_t %s_len = %d;" % (sym, len(data)))

    header += ["#ifdef __cplusplus", "}", "#endif", "#endif  // %s" % guard]

    with open(os.path.join(args.out_dir, args.name + ".h"), "w") as f:
        f.write("\n".join(header) + "\n")
    with open(os.path.join(args.out_dir, args.name + ".c"), "w") as f:
        f.write("\n".join(source) + "\n")


if __name__ == "__main__":
    main()
